---
- name: Change Hostname for {{ ansible_host }}
  hostname:
    name: "{{ k3s_hostname }}"

- name: Change value in /etc/hosts
  replace:
    path: "/etc/hosts"
    regexp: raspberrypi
    replace: '{{ k3s_hostname }}'
  register: host

- name: Enable container features to boot
  become: yes
  lineinfile:
    path: /boot/cmdline.txt
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: yes
    regexp: "^(.*rootwait.*)$"
  register: boot
  when: host.changed

- name: Reboot Pi
  reboot:
  when: boot.changed

- name: Install k3s
  become: no
  shell: curl -sfL https://get.k3s.io | sh -
  when: host.changed

- name: Extract join token
  shell: |
          cat /var/lib/rancher/k3s/server/node-token
  register: join_token

- name: Extract kube config
  shell: |
          cat /etc/rancher/k3s/k3s.yaml
  register: kube_config