---
- name: Clear workspace and mount dirs
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ rpi_os_workspace_dir }}"
    - "{{ rpi_os_mnt_dir }}"

- name: Make workspace and mount dirs
  file:
    path: "{{ item  }}"
    state: directory
  with_items:
    - "{{ rpi_os_workspace_dir }}"
    - "{{ rpi_os_mnt_dir }}"
    - "{{ rpi_os_mnt_dir }}/one"
    - "{{ rpi_os_mnt_dir }}/two"

- include: get_image.yaml

- include: mount_image.yaml

- include: configure_image.yaml

- include: write_image.yaml

- name: Clear workspace and mount dirs
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ rpi_os_workspace_dir }}"
    - "{{ rpi_os_mnt_dir }}"