---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian:buster

    steps:
      - name: Check out git repo.
        uses: actions/checkout@v2

      - name: Set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: pip3 install molecule docker yamllint ansible-lint

      - name: Run molecule test for imager
        run: cd roles/imager && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Run molecule test for rpi_proxy
        run: cd roles/rpi_proxy && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
