---

- name: Remove previous tmp config
  file:
    path: /var/tmp/kube_config
    state: absent

- name: Add kube config to file
  blockinfile:
    path: /var/tmp/kube_config
    create: yes
    marker: ""
    block: |
            {{ hostvars['pi_3b']['kube_config'].stdout }}

- name: Replace localhost IP with Pi IP
  replace:
    path: "/var/tmp/kube_config"
    regexp: '127.0.0.1'
    replace: "{{ hostvars['pi_3b']['ansible_host'] }}"


- name: Replace "default" with "pik3s"
  replace:
    path: "/var/tmp/kube_config"
    regexp: default
    replace: 'pik3s'

- name: Get new config
  shell: cat /var/tmp/kube_config
  register: kube_config_new

- name: Append kube config file
  blockinfile:
    path: /home/g/.kube/config
    backup: yes
    block: |
            {{ kube_config_new.stdout }}
